package ua.hillel.dbmanager;

public enum QueryType {
    AMOUNTGREATERNUMBEROFDIFFERENTEQUALS,
    CONTAININGGIVENNOMENCLATURE,
    NOTCONTAININGGIVENNOMENCLATUREORDERINGCURRENTDATE,
    CREATENEWORDERSHOPORDERTABULARPART,
    CREATENEWORDERSHOPORDERSHOPORDER,
    DELETEORDERS
}
